name: picar

channels:
  - conda-forge
  - apple

dependencies:
  - python=3.9
  - ipywidgets
  - pip
  - opencv
  - tqdm
  - jupyterlab
  - matplotlib
  - pip:
    - ploomber
    - pandas
    - numpy
    - wandb
